[mypy]
python_version = 3.10
files = nxl
check_untyped_defs = True
ignore_missing_imports = True
warn_unused_ignores = False
no_implicit_optional = False
disable_error_code =
    arg-type,
    assignment,
    attr-defined,
    call-overload,
    import-not-found,
    import-untyped,
    misc,
    no-any-return,
    no-redef,
    no-untyped-call,
    no-untyped-def,
    operator,
    return-value,
    type-arg,
    type-var,
    union-attr,
    unused-ignore,
    var-annotated
